#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME"

# Python
alias python=python3.11
alias pip=pip3

# Run a local version of zshrc that is not in sync with dotfiles
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc_local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc_local"
fi

