#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias dotfiles="/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME"

# Python
alias python=python3
alias pip=pip3

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/miro/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/miro/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/miro/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/miro/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

export PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"